package testing

var FluxEndToEndSkipList = map[string]string{
	// TODO(affo) these tests require a further study, because they produce wrong results (the expected output is wrong).
	"cumulative_sum_default":   "Reason TBD",
	"show_all_tag_keys":        "Reason TBD",
	"distinct":                 "Reason TBD",
	"multiple_range":           "Reason TBD",
	"difference_panic":         "Reason TBD",
	"filter_by_regex_function": "Reason TBD",
	"group_by_irregular":       "Reason TBD",
	"columns":                  "group key mismatch",
	"derivative":               "time bounds mismatch (engine uses now() instead of bounds on input table), and column order mismatch",
	"difference_columns":       "data write/read path loses columns x and y",
	"keys":                     "group key mismatch",
	"filter_by_regex":          "missing _stop",
	"filter_by_tags":           "missing _stop",
	"group":                    "missing _stop",
	"simple_max":               "missing _stop",
	"select_measurement":       "missing _stop",
	"select_measurement_field": "missing _stop",
	"pivot_mean":               "missing _start",
	"lowestAverage":            "missing _start and _stop",
	"meta_query_measurements":  "missing _start and _stop",
	"meta_query_fields":        "missing _start and _stop",
	"meta_query_keys":          "column order mismatch",
	"selector_preserve_time":   "column order mismatch",
	"count":                    "column order mismatch",
	"mean":                     "column order mismatch",
	"percentile_aggregate":     "column order mismatch",
	"percentile_tdigest":       "column order mismatch",
	"set_new_column":           "column order mismatch",
	"skew":                     "column order mismatch",
	"spread":                   "column order mismatch",
	"stddev":                   "column order mismatch",
	"sum":                      "column order mismatch",
	"set":                      "column order mismatch",
	"pivot_task_test":          "possible group key or column order mismatch",
	"percentile":               "time bounds mismatch (engine uses now() instead of bounds on input table)",

	// TODO(affo) results are not bounded, add a range() call maybe?
	"cov":                      "results must be bounded",
	"first":                    "results must be bounded",
	"highestAverage":           "results must be bounded",
	"highestMax":               "results must be bounded",
	"histogram":                "results must be bounded",
	"histogram_normalize":      "results must be bounded",
	"join":                     "results must be bounded",
	"join_across_measurements": "results must be bounded",
	"key_values":               "results must be bounded",
	"key_values_host_name":     "results must be bounded",
	"last":                     "results must be bounded",
	"max":                      "results must be bounded",
	"min":                      "results must be bounded",
	"sample":                   "results must be bounded",
	"shift":                    "results must be bounded",
	"shift_negative_duration":  "results must be bounded",
	"task_per_line":            "results must be bounded",
	"union":                    "results must be bounded",
	"union_heterogeneous":      "results must be bounded",
	"unique":                   "results must be bounded",
	"group_nulls":              "results must be bounded",
	"integral":                 "results must be bounded",
	"integral_columns":         "results must be bounded",
	"map":                      "results must be bounded",

	// TODO(affo) these tests are missing columns.
	"histogram_quantile":          "failed to read meta data: no column with label _measurement exists",
	"histogram_quantile_minvalue": "failed to read meta data: no column with label _measurement exists",
	"top":                         "failed to read meta data: no column with label _measurement exists",
	"covariance":                  "failed to read meta data: table has no _field column",
	"cumulative_sum":              "failed to read meta data: table has no _field column",
	"cumulative_sum_noop":         "failed to read meta data: table has no _field column",
	"increase":                    "failed to read meta data: table has no _value column",

	// TODO(affo) miscellaneous errors from query execution/compilation.
	//  it appears these occur when writing the input data. `to` may not be null safe.
	"fill_bool":                   "failed to read meta data: panic: interface conversion: interface {} is nil, not bool",
	"fill_float":                  "failed to read meta data: panic: interface conversion: interface {} is nil, not float64",
	"fill_int":                    "failed to read meta data: panic: interface conversion: interface {} is nil, not int64",
	"fill_string":                 "failed to read meta data: panic: interface conversion: interface {} is nil, not string",
	"fill_time":                   "failed to read meta data: panic: interface conversion: interface {} is nil, not uint64",
	"fill_uint":                   "failed to read meta data: panic: interface conversion: interface {} is nil, not uint64",
	"window_null":                 "failed to read meta data: panic: interface conversion: interface {} is nil, not float64",
	"covariance_missing_column_1": "need to support known errors in new test framework (https://github.com/influxdata/flux/issues/536)",
	"covariance_missing_column_2": "need to support known errors in new test framework (https://github.com/influxdata/flux/issues/536)",
	"drop_before_rename":          "need to support known errors in new test framework (https://github.com/influxdata/flux/issues/536)",
	"drop_referenced":             "need to support known errors in new test framework (https://github.com/influxdata/flux/issues/536)",
	"yield":                       "yield requires special test case (https://github.com/influxdata/flux/issues/535)",
	"string_max":                  "error: invalid use of function: *functions.MaxSelector has no implementation for type string (https://github.com/influxdata/platform/issues/224)",
	"group_ungroup":               "rpc error: code = Unknown desc = read: GroupKeys must not be empty when GroupBy or GroupExcept specified",
	"group_except":                "failed to read metadata",
	"keep_non_existent":           "keep error: column non_existent doesn't exist",
	"drop_non_existent":           "failed to compile query: var _drop_non_existent redeclared at drop_non_existent.flux|47:6-48:93",
	"null_as_value":               "null not supported as value in influxql (https://github.com/influxdata/platform/issues/353)",
	"to":                          "to functions are not supported in the testing framework (https://github.com/influxdata/flux/issues/77)",

	"rowfn_with_import":         "imported libraries are not visible in user-defined functions (https://github.com/influxdata/flux/issues/1000)",
	"string_trim":               "imported libraries are not visible in user-defined functions (https://github.com/influxdata/flux/issues/1000)",
	"window_group_mean_ungroup": "window trigger optimization modifies sort order of its output tables (https://github.com/influxdata/flux/issues/1067)",
	"string_interp":             "string interpolation not working as expected in flux (https://github.com/influxdata/flux/issues/756)",

	// Flaky test cases, see (https://github.com/influxdata/influxdb/issues/12891)
	"range":                 "flaky test (https://github.com/influxdata/influxdb/issues/12891)",
	"window_generate_empty": "flaky test (https://github.com/influxdata/influxdb/issues/12891)",
	"parse_regex":           "flaky test (https://github.com/influxdata/influxdb/issues/12891)",
}
